"""Context Engineering SDK - structured context modeling for AI agents."""

from context_engineering_sdk.core.types import (
    Role,
    AuthorKind,
    EvidenceType,
    SourceKind,
    BlockType,
    Priority,
    ToolCallStatus,
    ProviderKind,
    ToolType,
    ModelUsageStage,
    ModelUsageStatus,
    TaskStatus,
    Author,
    Ref,
    Message,
    MessageIndexRange,
    Summary,
    Task,
    TodoList,
    TaskState,
    ToolProvider,
    ToolCall,
    ToolState,
    ModelUsage,
    Session,
    EvidenceSource,
    EvidenceLinks,
    Evidence,
    ContextBlock,
    AgentInfo,
    Actor,
    Meta,
    SessionDocument,
    PutResult,
    RenderedBlock,
    MessagePart,
    AssembledInput,
    PruneDecision,
    ConflictRecord,
    RedactionRecord,
    Report,
    PrepareResult,
)
from context_engineering_sdk.core.errors import (
    ContextEngineError,
    SessionNotFoundError,
    VersionConflictError,
    BudgetExceededError,
    SelectorResolveError,
    EvidenceNotFoundError,
    SchemaValidationError,
    MigrationError,
    RedactionError,
    SummarizerError,
)
from context_engineering_sdk.config import (
    BudgetConfig,
    PruneConfig,
    RedactionConfig,
    ObservabilityConfig,
    SummaryConfig,
    RuntimeConfig,
)
from context_engineering_sdk.engine import DefaultContextEngine, create_context_engine

__version__ = "0.1.0"

__all__ = [
    # Enums
    "Role",
    "AuthorKind",
    "EvidenceType",
    "SourceKind",
    "BlockType",
    "Priority",
    "ToolCallStatus",
    "ProviderKind",
    "ToolType",
    "ModelUsageStage",
    "ModelUsageStatus",
    "TaskStatus",
    # Data classes
    "Author",
    "Ref",
    "Message",
    "MessageIndexRange",
    "Summary",
    "Task",
    "TodoList",
    "TaskState",
    "ToolProvider",
    "ToolCall",
    "ToolState",
    "ModelUsage",
    "Session",
    "EvidenceSource",
    "EvidenceLinks",
    "Evidence",
    "ContextBlock",
    "AgentInfo",
    "Actor",
    "Meta",
    "SessionDocument",
    "PutResult",
    "RenderedBlock",
    "MessagePart",
    "AssembledInput",
    "PruneDecision",
    "ConflictRecord",
    "RedactionRecord",
    "Report",
    "PrepareResult",
    # Config
    "BudgetConfig",
    "PruneConfig",
    "RedactionConfig",
    "ObservabilityConfig",
    "SummaryConfig",
    "RuntimeConfig",
    # Engine
    "DefaultContextEngine",
    "create_context_engine",
    # Errors
    "ContextEngineError",
    "SessionNotFoundError",
    "VersionConflictError",
    "BudgetExceededError",
    "SelectorResolveError",
    "EvidenceNotFoundError",
    "SchemaValidationError",
    "MigrationError",
    "RedactionError",
    "SummarizerError",
]
